name: ci

on:
  push:
    paths:
    - "*.py"
    - ".github/workflows/ci.yml"

jobs:

  core:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.8", "3.11"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - uses: actions/checkout@v4

    - run: pip install .[tests,lint]

    - run: flake8

    - run: mypy

    - run: pytest
